# Site settings
title: Toby and Code
email: toby@woller.io
description: > # this means to ignore newlines until "baseurl:"
  My journey to professional programmer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: 'http://woller.io' # the base hostname & protocol for your site
twitter_username: prereflect
github_username:  prereflect

# Build settings
markdown: kramdown
