# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Toby & Code
tagline:          'My coding journey'
description:      'I am documenting my journey to becomming a professional 
                   programmer. <a href="https://twitter.com/prereflect" 
                   target="_blank">@prereflect</a>'
url:              http://woller.io

author:
  name:           'Toby Woller'

paginate:         5

# Custom vars
version:          1.0.0
