# Site settings
title: Toby and Code
email: toby@woller.io
description: > # this means to ignore newlines until "baseurl:"
  My journey to programming and codeship.
baseurl: "" # the subpath of your site, e.g. /blog/
url: 'http://woller.io'  # the base hostname & protocol for your site
twitter_username: woller_io
github_username:  twoller

# Build settings
markdown: kramdown

paginate: 5

